Added APIs to translate voice to text
lance-condo0p/g-project-back pull request #1
Opened 2024-07-15 09:46 UTC by lance-condo0p

See OpenAPI and README.MD for the description.

2024-07-15 09:48 UTC, lance-condo0p commented
@bezroukov pls review

2024-07-16 16:42 UTC, bezroukov commented on src/main/kotlin/com/example/plugins/Authentication.kt
> +                }
Нужно убрать захардкоженные логин/пароль из кода, и перенести их в переменные окружения.

2024-07-16 16:44 UTC, bezroukov requested changes
Смотри комментарии

2024-07-16 16:45 UTC, bezroukov requested changes

2024-07-16 16:45 UTC, bezroukov commented on src/main/kotlin/com/example/Application.kt
> +//    client.close()
Не нужная строка

2024-07-30 16:10 UTC, lance-condo0p commented
@bezroukov все пофиксил. Проверь, пожалуйста.

2024-08-04 16:38 UTC, bezroukov approved these changes
*thumb_up*

2024-08-04 16:40 UTC, merged