Commands support
lance-condo0p/g-project-back pull request #2
Opened 2024-08-22 16:42 UTC by lance-condo0p

PR includes the following changes:
1) fixed local files creation on each request;
2) minor refactoring of plugins packaged (plugins split into "client" and "server" packages);
3) added unit tests;
4) supported commands URL (see OpenAPI for details).

2024-08-25 17:00 UTC, bezroukov commented on src/main/kotlin/com/example/routes/RequestRoutes.kt
> +//                    when (CommandType.values().findLast { it.type.equals(lexemes[i], ignoreCase = true) }) {
Ненужный комментарий

2024-08-25 17:01 UTC, bezroukov commented on src/test/kotlin/com/example/ApplicationTest.kt
> +
Нужно разделить тесты по файлам согласно проверяемым эндпоинтам

2024-08-25 17:01 UTC, bezroukov commented on src/test/kotlin/com/example/ApplicationTest.kt
> +    companion object {
Нужны тесты с замоканым яндексом

2024-08-25 17:01 UTC, bezroukov requested changes
Смотри комменты

2024-08-31 16:18 UTC, lance-condo0p commented
@bezroukov pls review changes

2024-08-31 16:40 UTC, bezroukov requested changes

2024-08-31 16:40 UTC, bezroukov commented on src/test/kotlin/com/example/tests/module/CommandTest.kt
> +        }
Имеет смысл отдельно проверять 
1. Что в результате команды на mock уходит ожидаемый запрос
2. Что ответ от mock преобразуется в ожидаемый формат

2024-09-10 18:50 UTC, lance-condo0p commented
@bezroukov 
pls check the updated version.

2024-09-12 15:57 UTC, bezroukov approved these changes

2024-09-12 16:00 UTC, merged